const usersData = [
    {
        userName: "Alice",
        email: "alice@example.com",
        password: "password123",
        profilePicture: "alice-pic.jpg",
        coverPicture: "alice-cover.jpg",
        friends: ["bob@example.com", "carol@example.com"],
        friendRequest: ["dave@example.com"],
        isAdmin: false,
        token: "",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        userName: "Bob",
        email: "bob@example.com",
        password: "password123",
        profilePicture: "bob-pic.jpg",
        coverPicture: "bob-cover.jpg",
        friends: ["alice@example.com", "dave@example.com"],
        friendRequest: [],
        isAdmin: false,
        token: "",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        userName: "Carol",
        email: "carol@example.com",
        password: "password123",
        profilePicture: "carol-pic.jpg",
        coverPicture: "carol-cover.jpg",
        friends: ["alice@example.com"],
        friendRequest: [],
        isAdmin: false,
        token: "",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        userName: "Dave",
        email: "dave@example.com",
        password: "password123",
        profilePicture: "dave-pic.jpg",
        coverPicture: "dave-cover.jpg",
        friends: ["bob@example.com"],
        friendRequest: ["alice@example.com"],
        isAdmin: false,
        token: "",
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];

module.exports = usersData;
